version: '3'

services:
  app:
    build: ./docker/node
    command: ["npm", "start"]
    ports:
      - 80:80
    networks: 
      - backend
    volumes:
      - ./:/app
    links:
      - database
    networks:
      - backend

  database:
    build: ./docker/mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks: 
      - backend

volumes:
  mongodb:

networks:
  backend: {}
