version: '3'

services:
  app_test:
    build: ./docker/node
    command: ["npm", "test"]
    networks: 
      - backend
    environment:
      - NODE_ENV=test
      - NODE_API_PORT=8080
    volumes:
      - ./:/app

networks:
  backend:
